// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vjlxarmtzpsbhiutamxe.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZqbHhhcm10enBzYmhpdXRhbXhlIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTcyNjQzMzEsImV4cCI6MjA3Mjg0MDMzMX0.OJHa68faK48nTe0ZZVOGID-NzVxmapoTuM9s3WF_HLo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});